/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ShippingRefundsRouteImport } from './routes/shipping-refunds'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OrderRouteImport } from './routes/order'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrderThankYouRouteImport } from './routes/order_.thank-you'
import { Route as ImgSplatRouteImport } from './routes/img/$'
import { Route as ApiAdminUploadRouteImport } from './routes/api/admin/upload'
import { Route as ApiAdminLogoutRouteImport } from './routes/api/admin/logout'
import { Route as ApiAdminLoginRouteImport } from './routes/api/admin/login'
import { Route as ApiAdminOrdersCsvRouteImport } from './routes/api/admin/orders/csv'
import { Route as ApiAdminEnquiriesCsvRouteImport } from './routes/api/admin/enquiries/csv'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingRefundsRoute = ShippingRefundsRouteImport.update({
  id: '/shipping-refunds',
  path: '/shipping-refunds',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderRoute = OrderRouteImport.update({
  id: '/order',
  path: '/order',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderThankYouRoute = OrderThankYouRouteImport.update({
  id: '/order_/thank-you',
  path: '/order/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const ImgSplatRoute = ImgSplatRouteImport.update({
  id: '/img/$',
  path: '/img/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUploadRoute = ApiAdminUploadRouteImport.update({
  id: '/api/admin/upload',
  path: '/api/admin/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminLogoutRoute = ApiAdminLogoutRouteImport.update({
  id: '/api/admin/logout',
  path: '/api/admin/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminLoginRoute = ApiAdminLoginRouteImport.update({
  id: '/api/admin/login',
  path: '/api/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminOrdersCsvRoute = ApiAdminOrdersCsvRouteImport.update({
  id: '/api/admin/orders/csv',
  path: '/api/admin/orders/csv',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminEnquiriesCsvRoute = ApiAdminEnquiriesCsvRouteImport.update({
  id: '/api/admin/enquiries/csv',
  path: '/api/admin/enquiries/csv',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/order': typeof OrderRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/shipping-refunds': typeof ShippingRefundsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/img/$': typeof ImgSplatRoute
  '/order/thank-you': typeof OrderThankYouRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/logout': typeof ApiAdminLogoutRoute
  '/api/admin/upload': typeof ApiAdminUploadRoute
  '/api/admin/enquiries/csv': typeof ApiAdminEnquiriesCsvRoute
  '/api/admin/orders/csv': typeof ApiAdminOrdersCsvRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/order': typeof OrderRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/shipping-refunds': typeof ShippingRefundsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/img/$': typeof ImgSplatRoute
  '/order/thank-you': typeof OrderThankYouRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/logout': typeof ApiAdminLogoutRoute
  '/api/admin/upload': typeof ApiAdminUploadRoute
  '/api/admin/enquiries/csv': typeof ApiAdminEnquiriesCsvRoute
  '/api/admin/orders/csv': typeof ApiAdminOrdersCsvRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/order': typeof OrderRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/shipping-refunds': typeof ShippingRefundsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/img/$': typeof ImgSplatRoute
  '/order_/thank-you': typeof OrderThankYouRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/logout': typeof ApiAdminLogoutRoute
  '/api/admin/upload': typeof ApiAdminUploadRoute
  '/api/admin/enquiries/csv': typeof ApiAdminEnquiriesCsvRoute
  '/api/admin/orders/csv': typeof ApiAdminOrdersCsvRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/faq'
    | '/gallery'
    | '/order'
    | '/privacy'
    | '/robots.txt'
    | '/shipping-refunds'
    | '/sitemap.xml'
    | '/terms'
    | '/img/$'
    | '/order/thank-you'
    | '/api/admin/login'
    | '/api/admin/logout'
    | '/api/admin/upload'
    | '/api/admin/enquiries/csv'
    | '/api/admin/orders/csv'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/faq'
    | '/gallery'
    | '/order'
    | '/privacy'
    | '/robots.txt'
    | '/shipping-refunds'
    | '/sitemap.xml'
    | '/terms'
    | '/img/$'
    | '/order/thank-you'
    | '/api/admin/login'
    | '/api/admin/logout'
    | '/api/admin/upload'
    | '/api/admin/enquiries/csv'
    | '/api/admin/orders/csv'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/faq'
    | '/gallery'
    | '/order'
    | '/privacy'
    | '/robots.txt'
    | '/shipping-refunds'
    | '/sitemap.xml'
    | '/terms'
    | '/img/$'
    | '/order_/thank-you'
    | '/api/admin/login'
    | '/api/admin/logout'
    | '/api/admin/upload'
    | '/api/admin/enquiries/csv'
    | '/api/admin/orders/csv'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  FaqRoute: typeof FaqRoute
  GalleryRoute: typeof GalleryRoute
  OrderRoute: typeof OrderRoute
  PrivacyRoute: typeof PrivacyRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  ShippingRefundsRoute: typeof ShippingRefundsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  ImgSplatRoute: typeof ImgSplatRoute
  OrderThankYouRoute: typeof OrderThankYouRoute
  ApiAdminLoginRoute: typeof ApiAdminLoginRoute
  ApiAdminLogoutRoute: typeof ApiAdminLogoutRoute
  ApiAdminUploadRoute: typeof ApiAdminUploadRoute
  ApiAdminEnquiriesCsvRoute: typeof ApiAdminEnquiriesCsvRoute
  ApiAdminOrdersCsvRoute: typeof ApiAdminOrdersCsvRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping-refunds': {
      id: '/shipping-refunds'
      path: '/shipping-refunds'
      fullPath: '/shipping-refunds'
      preLoaderRoute: typeof ShippingRefundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order': {
      id: '/order'
      path: '/order'
      fullPath: '/order'
      preLoaderRoute: typeof OrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order_/thank-you': {
      id: '/order_/thank-you'
      path: '/order/thank-you'
      fullPath: '/order/thank-you'
      preLoaderRoute: typeof OrderThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/img/$': {
      id: '/img/$'
      path: '/img/$'
      fullPath: '/img/$'
      preLoaderRoute: typeof ImgSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/upload': {
      id: '/api/admin/upload'
      path: '/api/admin/upload'
      fullPath: '/api/admin/upload'
      preLoaderRoute: typeof ApiAdminUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/logout': {
      id: '/api/admin/logout'
      path: '/api/admin/logout'
      fullPath: '/api/admin/logout'
      preLoaderRoute: typeof ApiAdminLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/login': {
      id: '/api/admin/login'
      path: '/api/admin/login'
      fullPath: '/api/admin/login'
      preLoaderRoute: typeof ApiAdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/orders/csv': {
      id: '/api/admin/orders/csv'
      path: '/api/admin/orders/csv'
      fullPath: '/api/admin/orders/csv'
      preLoaderRoute: typeof ApiAdminOrdersCsvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/enquiries/csv': {
      id: '/api/admin/enquiries/csv'
      path: '/api/admin/enquiries/csv'
      fullPath: '/api/admin/enquiries/csv'
      preLoaderRoute: typeof ApiAdminEnquiriesCsvRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  FaqRoute: FaqRoute,
  GalleryRoute: GalleryRoute,
  OrderRoute: OrderRoute,
  PrivacyRoute: PrivacyRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  ShippingRefundsRoute: ShippingRefundsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  ImgSplatRoute: ImgSplatRoute,
  OrderThankYouRoute: OrderThankYouRoute,
  ApiAdminLoginRoute: ApiAdminLoginRoute,
  ApiAdminLogoutRoute: ApiAdminLogoutRoute,
  ApiAdminUploadRoute: ApiAdminUploadRoute,
  ApiAdminEnquiriesCsvRoute: ApiAdminEnquiriesCsvRoute,
  ApiAdminOrdersCsvRoute: ApiAdminOrdersCsvRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
