import type { Metadata } from "next";
import { SiteHeader } from "@/components/site-header";
import { SiteFooter } from "@/components/site-footer";

export const metadata: Metadata = {
  title: "Delete your account — Coterie",
  description:
    "How to delete your Coterie account and associated data, what is removed, and how long anything is retained.",
};

const UPDATED = "July 2026";

export default function DeleteAccountPage() {
  return (
    <>
      <SiteHeader />
      <main className="container-page py-16">
        <span className="text-sm font-semibold uppercase tracking-widest text-clay">
          Coterie
        </span>
        <h1 className="mt-3 font-serif text-4xl font-semibold tracking-tight">
          Delete your account
        </h1>
        <p className="mt-2 text-sm text-ink/50">Last updated: {UPDATED}</p>
        <p className="mt-4 max-w-2xl text-sm text-ink/60">
          This page explains how to delete your <strong>Coterie</strong> account
          (developer: Coterie) and the data connected to it. You can delete your
          account yourself from inside the app at any time — no email or approval
          is required.
        </p>

        <div className="mt-10 max-w-2xl space-y-12 leading-relaxed text-ink/75">
          {/* ============== IN-APP STEPS ============== */}
          <section>
            <h2 className="font-serif text-2xl font-semibold text-ink">
              Delete from the app
            </h2>
            <ol className="mt-4 list-decimal space-y-2 pl-5">
              <li>Open Coterie and sign in.</li>
              <li>
                Tap the <strong>settings gear</strong> (or your avatar →{" "}
                <strong>Settings</strong>).
              </li>
              <li>
                Scroll to the <strong>Danger zone</strong> at the bottom.
              </li>
              <li>
                Tap <strong>Delete account</strong> and confirm by entering your
                password.
              </li>
            </ol>
            <p className="mt-4">
              Your account and its data are deleted immediately and the action
              cannot be undone.
            </p>
          </section>

          {/* ============== EMAIL FALLBACK ============== */}
          <section>
            <h2 className="font-serif text-2xl font-semibold text-ink">
              Can&rsquo;t sign in?
            </h2>
            <p className="mt-4">
              If you can no longer access your account, email{" "}
              <a
                href="mailto:haem.z10@gmail.com?subject=Coterie%20account%20deletion%20request"
                className="font-semibold text-clay underline-offset-4 hover:underline"
              >
                haem.z10@gmail.com
              </a>{" "}
              from the address on your account with the subject &ldquo;Account
              deletion request&rdquo;. We will verify your identity and delete
              your account and data within 30 days.
            </p>
          </section>

          {/* ============== WHAT IS DELETED ============== */}
          <section>
            <h2 className="font-serif text-2xl font-semibold text-ink">
              What gets deleted
            </h2>
            <p className="mt-4">
              When you delete your account, we permanently remove:
            </p>
            <ul className="mt-2 list-disc space-y-1 pl-5">
              <li>your profile — email, username, display name, avatar, and bio;</li>
              <li>your posts, photos, and captions;</li>
              <li>your comments and likes;</li>
              <li>your marketplace listings;</li>
              <li>
                communities you created, together with the posts and listings
                inside them;
              </li>
              <li>your direct messages and message threads;</li>
              <li>your follows, saved items, and notification preferences;</li>
              <li>notifications generated by or for you.</li>
            </ul>
          </section>

          {/* ============== DELETE SOME DATA ============== */}
          <section>
            <h2 className="font-serif text-2xl font-semibold text-ink">
              Deleting only some data
            </h2>
            <p className="mt-4">
              You don&rsquo;t have to delete your whole account to remove
              content. While signed in you can individually delete any of your
              own posts, photos, comments, marketplace listings, and communities,
              and update your profile details, from within the app.
            </p>
          </section>

          {/* ============== RETENTION ============== */}
          <section>
            <h2 className="font-serif text-2xl font-semibold text-ink">
              Data retention
            </h2>
            <p className="mt-4">
              Deletion removes your data from our live systems right away. Copies
              held in routine encrypted backups are purged within{" "}
              <strong>30 days</strong>. We retain no personal data beyond that,
              except where we are legally required to keep limited records (for
              example, to comply with tax, fraud-prevention, or other legal
              obligations), which are then securely deleted once no longer
              required.
            </p>
          </section>

          <p className="text-sm text-ink/50">
            For more on how we handle your information, see our{" "}
            <a
              href="/legal"
              className="font-semibold text-clay underline-offset-4 hover:underline"
            >
              Privacy Policy
            </a>
            .
          </p>
        </div>

        <a
          href="/"
          className="mt-10 inline-block rounded-full bg-ink px-6 py-3 text-sm font-semibold text-cream transition-transform hover:-translate-y-0.5"
        >
          ← Back to home
        </a>
      </main>
      <SiteFooter />
    </>
  );
}
